### PR TITLE
Register the Hibernate validation message bundle

### LINKED ISSUE #410: Hibernate message bundle should be functional
### Expected Behavior

The constraint violation should come though with the translated text, for example `must be a valid URL`

### Actual Behaviour

The constraint error comes through as a message code, for example `{org.hibernate.validator.constraints.URL.message}`

### Steps To Reproduce

Run the test `"test validated bean invalid bean"` and you will see the issue. This test was disabled for some reason.

### Environment Information

_No response_

### Example Application

_No response_

### Version

micronaut-hibernate-validator v4.3.0 (Micronaut 4.4 or 4.5)

### PR DESCRIPTION
**Pull request by kevin-wise**
Register the Hibernate validation message bundle, so that messages are interpolated correctly. Fixes #410 .

I'm not really sure what made this necessary. I do know that it broke between Micronaut 3 and 4.
Of course, I'm open to other ideas. This was the first one I had that worked.

### CODE REVIEW

File: hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/HibernateMessageBundle.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package io.micronaut.configuration.hibernate.validator;
+
+import io.micronaut.context.annotation.Requires;
+import io.micronaut.context.i18n.ResourceBundleMessageSource;
+import io.micronaut.core.order.Ordered;
+import jakarta.inject.Singleton;
+
+@Singleton
+@Requires(bean = MicronautHibernateValidator.class)
```
Comment (kevin-wise) [inline hibernate-validator/src/main/java/io/micronaut/configuration/hibernate/validator/HibernateMessageBundle.java]: Would it be better to use this?
```suggestion
@Requires(resources = "classpath:org/hibernate/validator/ValidationMessages.properties")
```
